# Generated by Django 5.0.3 on 2026-07-03 10:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('balance_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=20)),
                ('memo', models.CharField(max_length=64, unique=True)),
                ('ton_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('amount_ton', models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('expired', 'expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payments.account')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=128, unique=True)),
                ('currency', models.CharField(choices=[('TON', 'TON'), ('USDT', 'USDT')], max_length=8)),
                ('amount_paid', models.DecimalField(decimal_places=9, max_digits=20)),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=20)),
                ('from_address', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.account')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='payments.invoice')),
            ],
        ),
    ]
